### ISSUE TITLE
 cannot find package "github.com/simagix/hatchet

### ISSUE THREAD

**Issue by sameergavkar** [simagix/hatchet#37]
Hi Team, We are getting below Error

[root@RCPPPMPOSAPPN3 hatchet]# ./build.sh 
main/hatchet.go:9:2: cannot find package "github.com/simagix/hatchet" in any of:
        /usr/lib/golang/src/github.com/simagix/hatchet (from $GOROOT)
        /root/go/src/github.com/simagix/hatchet (from $GOPATH)

root@RCPPPMPOSAPPN3 hatchet]# go version
go version go1.9.4 linux/amd64

**Comment by simagix** [comment]
It's your Go environment. A similar problem, https://github.com/simagix/hatchet/issues/35, was closed.  Please checkout the Go documents.
